import { Heart, Instagram, MapPin, MessageCircle, Package, Phone, ShieldCheck, Truck } from "lucide-react";
import { Link } from "wouter";
import type { Product } from "@/data/storefront";
import { money } from "@/data/storefront";

export function ProductCard({ product, onAdd, favorite, onFavorite }: { product: Product; onAdd: () => void; favorite?: boolean; onFavorite?: () => void }) {
  return <article className="product-card group relative flex min-w-[238px] flex-1 flex-col overflow-hidden rounded-2xl border border-[#e7e5e2] bg-white"><div className="relative aspect-[1.05] overflow-hidden bg-[#f3f5f4]"><Link href={`/product/${product.id}`}><img src={product.image} alt={product.name} loading="lazy" decoding="async" className="product-image h-full w-full object-cover mix-blend-multiply" /></Link>{product.badge && <span className="absolute left-3 top-3 rounded-md bg-[#f36f32] px-2.5 py-1 text-[10px] font-extrabold tracking-wide text-white shadow-sm">{product.badge}</span>}{onFavorite && <button onClick={onFavorite} aria-label="Favorilere ekle" className={`absolute right-3 top-3 grid h-9 w-9 place-items-center rounded-full bg-white/90 shadow-sm transition hover:bg-white hover:shadow-md ${favorite ? "text-[#f36f32]" : "text-[#4e524f]"}`}><Heart size={17} fill={favorite ? "currentColor" : "none"} /></button>}<button onClick={onAdd} className="absolute bottom-3 left-3 right-3 rounded-lg bg-[#203f36] py-2.5 text-[11px] font-bold text-white opacity-100 shadow-lg transition duration-200 hover:bg-[#152f27] md:translate-y-2 md:opacity-0 md:group-hover:translate-y-0 md:group-hover:opacity-100">SEPETE EKLE</button></div><div className="flex flex-1 flex-col p-4"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-[#f36f32]">{product.category}</p><Link href={`/product/${product.id}`} className="mt-2 min-h-[42px] text-[14px] font-semibold leading-5 text-[#202522] hover:text-[#f36f32]">{product.name}</Link><div className="mt-3 flex items-center gap-1 text-[11px] text-[#777b76]"><span className="text-[#f36f32]">★</span><span>{product.rating}</span><span className="text-[#d2d4d0]">·</span><span>32 değerlendirme</span></div><div className="mt-4 flex items-end gap-2"><strong className="text-[18px] font-extrabold text-[#203f36]">{money(product.price)}</strong>{product.oldPrice && <del className="text-xs text-[#9da19d]">{money(product.oldPrice)}</del>}</div></div></article>;
}

export function Benefits() { return <section className="mx-auto grid max-w-[1400px] gap-3 px-4 py-10 sm:grid-cols-3 lg:px-8 lg:py-14"><div className="flex items-center gap-4 rounded-2xl border border-[#e5e7e3] bg-white p-5"><Truck className="text-[#f36f32]" size={26} /><div><h3 className="text-sm font-extrabold">Hızlı teslimat</h3><p className="mt-1 text-xs text-[#798079]">Aynı gün kargoya verilir.</p></div></div><div className="flex items-center gap-4 rounded-2xl border border-[#e5e7e3] bg-white p-5"><ShieldCheck className="text-[#f36f32]" size={26} /><div><h3 className="text-sm font-extrabold">Güvenli alışveriş</h3><p className="mt-1 text-xs text-[#798079]">256 bit SSL ile korumalı.</p></div></div><div className="flex items-center gap-4 rounded-2xl border border-[#e5e7e3] bg-white p-5"><Package className="text-[#f36f32]" size={26} /><div><h3 className="text-sm font-extrabold">Kolay iade</h3><p className="mt-1 text-xs text-[#798079]">14 gün içinde ücretsiz iade.</p></div></div></section>; }

export function StoreFooter() {
  return <footer className="bg-[#203f36] px-4 py-14 text-white lg:px-8">
    <div className="mx-auto max-w-[1400px]">
      <div className="grid gap-12 border-b border-white/10 pb-12 lg:grid-cols-[1.35fr_1fr_1fr_1.25fr]">
        <div><Link href="/" className="text-3xl font-black tracking-[-.08em]">MIRAJU<span className="text-[#f36f32]">.</span></Link><p className="mt-1 text-[10px] font-extrabold uppercase tracking-[.22em] text-[#f5c2a7]">Professionel</p><p className="mt-5 max-w-[310px] text-sm leading-6 text-[#b8c9bf]">Her zaman sizi dinledik. Profesyonel ürünleri, kaliteyi ulaşılabilir kılmak için Miraju güvencesiyle sunuyoruz.</p><div className="mt-6 flex gap-2"><a aria-label="Instagram" href="https://instagram.com/mirajutoptan" target="_blank" rel="noreferrer" className="grid h-9 w-9 place-items-center rounded-full border border-white/15 text-[#f5c2a7] transition hover:border-[#f36f32] hover:bg-[#f36f32] hover:text-white"><Instagram size={16} /></a><a aria-label="WhatsApp" href="https://wa.me/905309153518" target="_blank" rel="noreferrer" className="grid h-9 w-9 place-items-center rounded-full border border-white/15 text-[#f5c2a7] transition hover:border-[#f36f32] hover:bg-[#f36f32] hover:text-white"><MessageCircle size={16} /></a></div></div>
        <div><h3 className="text-xs font-extrabold uppercase tracking-[.16em] text-[#f5c2a7]">Hakkımızda</h3><div className="mt-5 grid gap-3 text-sm text-[#b8c9bf]"><Link className="transition hover:text-white" href="/info/hakkimizda">Hakkımızda</Link><Link className="transition hover:text-white" href="/info/iletisim">İletişim</Link><Link className="transition hover:text-white" href="/info/magaza">Mağaza bilgilerimiz</Link><a className="flex items-center gap-2 transition hover:text-white" href="https://instagram.com/mirajutoptan" target="_blank" rel="noreferrer"><Instagram size={14} /> @mirajutoptan</a></div></div>
        <div><h3 className="text-xs font-extrabold uppercase tracking-[.16em] text-[#f5c2a7]">Yardım</h3><div className="mt-5 grid gap-3 text-sm text-[#b8c9bf]"><Link className="transition hover:text-white" href="/info/gizlilik">Gizlilik sözleşmesi</Link><Link className="transition hover:text-white" href="/info/mesafeli-satis">Mesafeli satış sözleşmesi</Link><Link className="transition hover:text-white" href="/info/kullanim">Kullanım koşulları</Link><Link className="transition hover:text-white" href="/info/kvkk">KVKK Aydınlatma Metni</Link><Link className="transition hover:text-white" href="/info/teslimat">Teslimat & kargo</Link><Link className="transition hover:text-white" href="/info/iade">İade koşulları</Link><Link className="transition hover:text-white" href="/info/cerez">Çerez Politikası</Link><Link className="transition hover:text-white" href="/info/sss">S.S.S.</Link></div></div>
        <div><h3 className="text-xs font-extrabold uppercase tracking-[.16em] text-[#f5c2a7]">Bize ulaşın</h3><div className="mt-5 grid gap-4 text-sm text-[#b8c9bf]"><a className="flex items-start gap-3 transition hover:text-white" href="https://maps.google.com/?q=1526+Sk+No+2/C+Ulubey+İş+Merkezi+Halkapınar+İzmir" target="_blank" rel="noreferrer"><MapPin className="mt-0.5 shrink-0 text-[#f36f32]" size={16} /><span>1526 Sk No:2/C Ulubey İş Merkezi<br />Halkapınar / İzmir</span></a><a className="flex items-center gap-3 transition hover:text-white" href="tel:+905309153518"><Phone className="shrink-0 text-[#f36f32]" size={16} />+90 530 915 35 18</a><a className="flex items-center gap-3 transition hover:text-white" href="https://wa.me/905309153518" target="_blank" rel="noreferrer"><MessageCircle className="shrink-0 text-[#f36f32]" size={16} />WhatsApp’tan yazın</a></div></div>
      </div>
      <div className="grid gap-7 border-b border-white/10 py-8 md:grid-cols-[1fr_1.2fr]"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 shrink-0 text-[#f36f32]" size={22} /><div><h3 className="text-xs font-extrabold uppercase tracking-[.16em] text-white">Güvenli alışveriş</h3><p className="mt-2 max-w-[500px] text-xs leading-5 text-[#8ea79a]">MIRAJU’da kredi kartı bilgileriniz banka sanal POS güvencesindedir. Tüm bankaların VISA ve MASTERCARD kartları geçerlidir.</p></div></div><div className="flex flex-wrap items-center gap-2 md:justify-end"><span className="rounded border border-white/15 px-3 py-2 text-[10px] font-bold text-[#b8c9bf]">256-BİT SSL GÜVENLİ</span><span className="rounded border border-white/15 px-3 py-2 text-[10px] font-bold text-[#b8c9bf]">VISA</span><span className="rounded border border-white/15 px-3 py-2 text-[10px] font-bold text-[#b8c9bf]">MASTERCARD</span></div></div>
      <div className="flex flex-col justify-between gap-3 pt-5 text-xs text-[#8ea79a] sm:flex-row"><span>© 2026 Miraju Professionel. Tüm hakları saklıdır.</span><span>3.000 TL ve üzeri siparişlerde kargo ücretsiz.</span></div>
    </div>
  </footer>;
}
