import { ArrowLeft, MapPin, MessageCircle, Phone } from "lucide-react";
import { Link, useRoute } from "wouter";
import { StoreFooter } from "@/components/storefront/StoreChrome";

const pages: Record<string, { title: string; eyebrow: string; body: string[] }> = {
  hakkimizda: { title: "Miraju hakkında", eyebrow: "MIRAJU PROFESSIONEL", body: ["2016 yılında kurulan firmamız, müşterilerine kaliteli ürün ve güvenilir hizmet sunma amacıyla faaliyetlerine başlamıştır. Kurulduğumuz günden bu yana yenilikçi yaklaşımımız, müşteri memnuniyeti odaklı hizmet anlayışımız ve işimize duyduğumuz bağlılıkla sürekli gelişmeyi hedefliyoruz.", "Sektördeki deneyimimizi, güncel çözümler ve profesyonel hizmet anlayışıyla birleştirerek müşterilerimizin ihtiyaçlarına en doğru şekilde cevap veriyoruz. Her projeye özel çözümler sunarken kalite, güven ve şeffaflık ilkelerimizden ödün vermiyoruz.", "Bugün, güçlü ekibimiz ve değerli iş ortaklarımızla birlikte sürdürülebilir başarıya odaklanıyor; müşterilerimizle uzun vadeli ve güvene dayalı ilişkiler kurmayı önemsiyoruz."] },
  iletisim: { title: "İletişim - MIRAJU PROFESSIONEL", eyebrow: "BİZE ULAŞIN", body: ["Adres: 1526 Sk No:2/C Ulubey İş Merkezi Halkapınar / İzmir", "Tel / WhatsApp: +90 530 915 35 18", "Instagram: @mirajutoptan", "Çalışma Saatleri: Hafta içi 09:00 - 18:00"] },
  magaza: { title: "Mağaza bilgilerimiz", eyebrow: "MIRAJU MAĞAZA", body: ["MIRAJU Depo: 1526 Sk No:2/C Ulubey İş Merkezi Halkapınar / İzmir", "Tel: +90 530 915 35 18", "Instagram: @mirajutoptan"] },
  kullanim: { title: "Kullanım Koşulları - MIRAJU PROFESSIONEL", eyebrow: "YASAL BİLGİ", body: ["SATICI: MIRAJU PROFESSIONEL — Adres: 1526 Sk No:2/C Ulubey İş Merkezi Halkapınar / İzmir — Tel: +90 530 915 35 18 — Instagram: @mirajutoptan", "MIRAJU PROFESSIONEL web sitesini kullanarak kullanım koşullarını kabul etmiş olursunuz. Fiyatlar TL ve KDV dahildir. Toptan alımlarda WhatsApp üzerinden özel fiyat verilir.", "3.000 TL ve üzeri siparişlerde ücretsiz kargo. Siparişler aynı gün kargoya verilir."] },
  gizlilik: { title: "Gizlilik Sözleşmesi - MIRAJU PROFESSIONEL", eyebrow: "YASAL BİLGİ", body: ["Bu sayfada yer alan güvenlik ve gizlilik kuralları yaptığınız alışverişlerde ve vermiş olduğunuz kişisel bilgilerdeki güvenlik ve gizlilik sınırlarını belirlemek amacı ile konulmuştur.", "MIRAJU gizlilik politikası neleri kapsar? Bu gizlilik politikası miraju.com.tr URL'i ile başlayan tüm sitelerde geçerlidir.", "Tüm bilgileriniz hiçbir şekilde üçüncü kişiler ile paylaşılmaz.", "MIRAJU'da bir ürün satın alırken kullandığınız kredi kartı bilgileriniz banka sanal POS güvencesindedir, üçüncü şahıslar kredi kartı bilgilerinizi göremezler.", "MIRAJU'dan satın aldığınız ürünlerin hasarsız, eksiksiz, doğru adrese ve zamanında fatura ile birlikte tesliminden MIRAJU sorumludur.", "MIRAJU için: Üyelik bilgileriniz sadece MIRAJU çalışanları tarafından, kredi kartı bilgileriniz ise sadece banka tarafından görülür."] },
  kvkk: { title: "KVKK Aydınlatma Metni - MIRAJU PROFESSIONEL", eyebrow: "YASAL BİLGİ", body: ["Veri Sorumlusu: MIRAJU PROFESSIONEL — Adres: 1526 Sk No:2/C Ulubey İş Merkezi Halkapınar / İzmir — Tel: +90 530 915 35 18 — Instagram: @mirajutoptan", "Ad, soyad, telefon, e-posta, adres bilgileriniz sadece sipariş teslimatı ve müşteri hizmetleri için kullanılır. Verileriniz kargo firması ve ödeme altyapısı dışında paylaşılmaz."] },
  "mesafeli-satis": { title: "Mesafeli Satış Sözleşmesi - MIRAJU PROFESSIONEL", eyebrow: "YASAL BİLGİ", body: ["MADDE 1 - SÖZLEŞMENİN TARAFLARI — SATICI: MIRAJU PROFESSIONEL - 1526 Sk No:2/C Ulubey İş Merkezi Halkapınar / İzmir - Tel: +90 530 915 35 18", "MADDE 2 - SÖZLEŞMENİN KONUSU: Alıcının Satıcıya ait web sitesinden elektronik ortamda sipariş verdiği mal/hizmetin satışı ve teslimi ile ilgili olarak 6502 sayılı Tüketicilerin Korunması Hakkındaki Kanun ve Mesafeli Sözleşmeler Yönetmeliği hükümleri gereğince tarafların hak ve yükümlülüklerinin saptanmasıdır.", "MADDE 4 - TESLİMAT: Mal/hizmet, alıcının teslimini talep etmiş olduğu adreste teslim edilecektir.", "MADDE 5 - TESLİMAT MASRAFLARI: Teslimat masrafları alıcıya aittir. 3.000 TL üzeri siparişlerde kargo ücretsizdir.", "MADDE 14 - CAYMA HAKKI: Alıcı, sözleşme konusu mal/hizmetin kendisine tesliminden itibaren 14 gün içinde cayma hakkını kullanabilir.", "MADDE 15 - CAYMA HAKKI KULLANILAMAYACAK ÜRÜNLER: Niteliği itibarıyla iade edilemeyecek, hijyenik ürünler, kozmetik malzemelerinde ambalajı açılmamış şartı aranır."] },
  teslimat: { title: "Kargo ve Teslimat - MIRAJU PROFESSIONEL", eyebrow: "SİPARİŞ DESTEĞİ", body: ["Depo: 1526 Sk No:2/C Ulubey İş Merkezi Halkapınar / İzmir", "Ücretsiz Kargo: 3.000 TL ve üzeri siparişlerde ücretsiz kargo.", "Teslimat: Stok müsait ise 24 saat içinde kargoya verilir. İzmir içi aynı gün teslimat mümkün.", "Takip: Kargo takip numarası WhatsApp/SMS ile gönderilir."] },
  iade: { title: "İade ve Değişim - MIRAJU PROFESSIONEL", eyebrow: "SİPARİŞ DESTEĞİ", body: ["İade Süresi: 14 gün içinde iade talebi oluşturabilirsiniz.", "İade Adresi: MIRAJU PROFESSIONEL, 1526 Sk No:2/C Ulubey İş Merkezi Halkapınar / İzmir - Tel: +90 530 915 35 18", "Hijyen Kuralı: Pens, törpü, buffer, oje gibi hijyen ürünlerinde ambalaj açıldıysa veya kullanıldıysa iade alınamaz."] },
  cerez: { title: "Çerez Politikası - MIRAJU PROFESSIONEL", eyebrow: "YASAL BİLGİ", body: ["Zorunlu çerezler sepet ve oturum yönetimi için gereklidir. Analitik çerezler site performansını ölçmek için kullanılır. Tercihlerinizi tarayıcı ayarlarınızdan yönetebilirsiniz."] },
  sss: { title: "Sıkça Sorulan Sorular - MIRAJU PROFESSIONEL", eyebrow: "YARDIM MERKEZİ", body: ["Toptan fiyat alabilir miyim? Evet. WhatsApp +90 530 915 35 18 veya Instagram @mirajutoptan DM'den yazın.", "Mağazanız var mı? Evet. 1526 Sk No:2/C Ulubey İş Merkezi Halkapınar / İzmir", "Kargo ne kadar? 79 TL. 3.000 TL üzeri ücretsiz.", "Orijinal ürün mü? Evet. Momo, Staleks ve tüm ürünler faturalı ve orijinal."] },
};

export default function InfoPage() {
  const [, params] = useRoute<{ slug: string }>("/info/:slug");
  const page = pages[params?.slug || ""] || pages.hakkimizda;
  return <div className="storefront min-h-screen bg-[#f7f8f6] text-[#202522]"><header className="border-b border-[#e5e7e3] bg-white px-4 py-5"><div className="mx-auto flex max-w-[1100px] items-center justify-between"><Link href="/" className="text-2xl font-black tracking-[-.09em] text-[#203f36]">miraju<span className="text-[#f36f32]">.</span></Link><Link href="/" className="text-xs font-bold text-[#203f36] hover:text-[#f36f32]">Mağazaya dön</Link></div></header><main className="mx-auto max-w-[1000px] px-4 py-12 lg:px-8"><Link href="/" className="inline-flex items-center gap-2 text-xs font-bold text-[#53635a] hover:text-[#f36f32]"><ArrowLeft size={15} /> Ana sayfaya dön</Link><section className="mt-6 rounded-[2rem] bg-[#203f36] p-8 text-white sm:p-12"><p className="text-[10px] font-extrabold uppercase tracking-[.2em] text-[#f5c2a7]">{page.eyebrow}</p><h1 className="mt-4 text-4xl font-black tracking-[-.07em] sm:text-6xl">{page.title}</h1><div className="mt-8 grid gap-5 sm:grid-cols-2">{page.body.map((paragraph) => <p key={paragraph} className="text-sm leading-7 text-[#c5d4cb]">{paragraph}</p>)}</div></section>{params?.slug === "iletisim" || params?.slug === "magaza" ? <section className="mt-6 grid gap-4 sm:grid-cols-3"><a href="tel:+905309153518" className="rounded-2xl border border-[#e2e7e3] bg-white p-5 text-sm font-bold text-[#203f36]"><Phone className="mb-4 text-[#f36f32]" size={20} />+90 530 915 35 18</a><a href="https://wa.me/905309153518" target="_blank" rel="noreferrer" className="rounded-2xl border border-[#e2e7e3] bg-white p-5 text-sm font-bold text-[#203f36]"><MessageCircle className="mb-4 text-[#f36f32]" size={20} />WhatsApp’tan yazın</a><a href="https://maps.google.com/?q=1526+Sk+No+2/C+Ulubey+İş+Merkezi+Halkapınar+İzmir" target="_blank" rel="noreferrer" className="rounded-2xl border border-[#e2e7e3] bg-white p-5 text-sm font-bold text-[#203f36]"><MapPin className="mb-4 text-[#f36f32]" size={20} />Halkapınar / İzmir</a></section> : null}</main><StoreFooter /></div>;
}
